name: Images

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am UTC
  release:
    types: [ published ]
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - '.github'
  workflow_dispatch:

jobs:
  docker:
    name: "Build & Push"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Split repo name
        uses: jungwinter/split@v2
        id: split_reponame
        with:
          separator: '/'
          msg: ${{ github.repository }}

      - name: Setup repo name to lowercase
        id: reponame
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ steps.split_reponame.outputs._1 }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.REGISTRY }}/${{ steps.reponame.outputs.lowercase }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
